export const shop = {
  shopByCategory: [
    "Skincare Regimens",
    "Lash & Brow",
    "Eye Creams & Treatments",
    "Face Serums & Treatments",
    "Face Masks",
    "Moisturizers",
    "Cleansers & Makeup Removers",
    "Toners",
    "Sun Protection",
    "Tools & Accessories",
    "Hand & Body",
  ],

  shopByConcern: [
    "Anti-Aging",
    "Acne, Pores & Blackheads",
    "Dark Spots & Uneven Skin Tone",
    "Sensitivity & Visible Redness",
    "Dull & Tired Skin",
    "Dry Skin",
    "Teen Acne",
  ],

  shopByProductLine: [
    "Redefine",
    "Reverse",
    "Unblemish",
    "Soothe",
    "Recharge",
    "Spotless",
    "Enhancements",
    "Pro Skincare Tools",
    "Essentials",
    "All Products",
  ],
};
export const featured = [
  "Special Offers",
  "Before and Afters",
  "New Total RF Serum",
  "Spotless for Teens",
  "Self-Care Essentials",
];
export const ourstory = [
  "R+F Difference",
  "Personalized Service",
  "Explore Our Regimens",
  "Our Founders",
  "Our Impact",
];
export const bestSellers = [
  {
    thumb_image:
      "https://www.rodanandfields.com/en-us/medias/ENFM030-Thumbnail-458x458.jpg?context=bWFzdGVyfGltYWdlc3wyNTQ2MHxpbWFnZS9qcGVnfGltYWdlcy9oZmQvaGQ2LzE0ODgyMTk1ODk4Mzk4LmpwZ3wyYThhMjQ0NTc4YjI1ZmQ1ODY3MDE5NGMyYjk3MjA2MTRmNDQ2MzdmOGVhYzMxYTFmMDk1YmIyY2Q5NDhjMzIw",
    product_name: "Total RF Serum",
    description:
      "Our most comprehensive anti-aging serum features RF TriEnergy Complex that energizes millions of surface skin cells by 200% to address all key signs of skin aging.",
    price: 175,
    price_type: "Retail Price",
    ratings: 4.5,
    reviews: 3374,
    images: [
      "https://www.rodanandfields.com/en-us/medias/ENFM030-Global-720x600-Desktop.jpg?context=bWFzdGVyfGltYWdlc3wzNzU0NHxpbWFnZS9qcGVnfGltYWdlcy9oMzQvaDQwLzEzNjkzOTY1NTk4NzUwLmpwZ3xlODg0YWM5YjBiZjM0M2I4MzMyYjE5NDMzMmZjMjg4ZjM1MDE1ZDg4YTI1NjFhNTJlNjg5ZWRjYWYzMTY5NDQ5",
      "https://www.rodanandfields.com/en-us/medias/TRFS-Lifestyle-Product-Global-570x570.jpg?context=bWFzdGVyfGltYWdlc3w1MTE3NnxpbWFnZS9qcGVnfGltYWdlcy9oZDYvaDdlLzEzNjYyODA0NzM4MDc4LmpwZ3w5NDA1Mzc5OGFjOTI1NzU1ZmMyZjlhY2Y0ZjdhNmI4NWU3NmVlMWIxYzY5OWMxNGRlMGIxZjExOWZkNmYyMGNk",
      "https://www.rodanandfields.com/en-us/medias/TRFS-Texture-Global-570x570.jpg?context=bWFzdGVyfGltYWdlc3wxMzI5NnxpbWFnZS9qcGVnfGltYWdlcy9oMGEvaDA4LzEzNjYyODA0ODM2MzgyLmpwZ3w2YjllODQwYjI1YTI2Y2I5YzQ5ZTU0MzMzMzgxNWJiM2I2ZDBkZDIyZGY2YWRhMjA4MTU1MTczYTlkYmEwMjI0",
      "https://www.rodanandfields.com/en-us/medias/TRFS-Application-GIF-Global-570x570.gif?context=bWFzdGVyfGltYWdlc3wxNjcxNDZ8aW1hZ2UvZ2lmfGltYWdlcy9oY2EvaDM0LzEzNjYyODA0NjA3MDA2LmdpZnw3YTUyMTM3ZjZlYzU4NTIwNWJhMWY4ZGYzYmM0NTE4ZWJmMWM3NGZiNTViZDYyNmMyY2JkNzgwZmY2YTg5ZTYw",
    ],
    video: "https://youtu.be/jKIzPp2moeo",
  },
  {
    thumb_image:
      "https://www.rodanandfields.com/en-us/medias/ENHLSH01-detail.jpg?context=bWFzdGVyfGltYWdlc3wzMjIzMHxpbWFnZS9qcGVnfGltYWdlcy9oMTMvaDYwLzg4MjE4NDk2ODYwNDYuanBnfDMzOTMxMWRkOGUyMWZiOTQzY2NhYzhlODM4NTFhZDcxZTU3Yzg0NGIyMDZmODE2N2M0YTBhZDUzZDg2MGEyNzI",
    product_name: "R + F Lash Boost",
    description:
      "#1 Premium Lash Serum in the U.S. in 2021!* Our famous lash conditioning serum is applied nightly to promote the appearance of longer, stronger and darker-looking lashes (or brows!)",
    price: 155,
    price_type: "Retail Price",
    ratings: 0,
    reviews: 0,
    images: [],
  },
  {
    thumb_image: "",
    product_name: "",
    description: "",
    price: 0,
    price_type: "Retail Price",
    ratings: 0,
    votes: 0,
    images: [],
  },
  {
    thumb_image: "",
    product_name: "",
    description: "",
    price: 0,
    price_type: "Retail Price",
    ratings: 0,
    votes: 0,
    images: [],
  },
  {
    thumb_image: "",
    product_name: "",
    description: "",
    price: 0,
    price_type: "Retail Price",
    ratings: 0,
    votes: 0,
    images: [],
  },
  {
    thumb_image: "",
    product_name: "",
    description: "",
    price: 0,
    price_type: "Retail Price",
    ratings: 0,
    votes: 0,
    images: [],
  },
  {
    thumb_image: "",
    product_name: "",
    description: "",
    price: 0,
    price_type: "Retail Price",
    ratings: 0,
    votes: 0,
    images: [],
  },
  {
    thumb_image: "",
    product_name: "",
    description: "",
    price: 0,
    price_type: "Retail Price",
    ratings: 0,
    votes: 0,
    images: [],
  },
];
